language: minimal 

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libopenmpi-dev
      - libfftw3-dev
   
git:
  depth: false
    
branches:
  only: 
  - master

script:
  - cd src && make FFTW="-I/usr/include -lfftw3" COV="-fprofile-arcs -ftest-coverage"
  - cd ../sample/recv_func_fwd && ../../bin/recv_func_fwd recv_func_fwd.in
  - cd ../disper_fwd && ../../bin/disper_fwd disper_fwd.in

after_success:
  - bash <(curl -s https://codecov.io/bash)
