language: minimal 

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libopenmpi-dev
      - libfftw3-dev
   
git:
  depth: false
    
branches:
  only: 
  - master

script:
  - cd src && make FFTW="-I/usr/include -lfftw3" COV="-fprofile-arcs -ftest-coverage"
  - cd ../sample/joint_inv && ../../bin/recv_func_fwd recv_func_fwd.in
