language: minimal 

addons:
  apt:
    packages:
      - gfortran
      - liblapack-dev
      - libopenmpi-dev
      - libfftw3-dev
   
git:
  depth: false
    
branches:
  only: 
  - master

script:
  cd src && make FFTW="-I/usr/include -lfftw3" 
